### ISSUE TITLE
Make changes to Syke moth form

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji#559]
Changes to form settings:

    Sidebar:
        Ilmoita -> Tallenna
        Remove Templates / Esitäytetyt -link
    Named place form
        Add missing fields:
            Notes
            Keywords
    Prepopulated document should contain these fields:
        Locality name
        Locality description
        Moth trap type
    Form
        Make end date field mandatory
        Remove New place -button
        Move fields koiraiden yksilömäärä & naarainen yksilömäärä right after Määrä, before Lisätiedot.

**Comment by rpulkka** [comment]
Testable here: https://dev.laji.fi/project/MHL.1136/form/places

Tried to implement everything else, except the keywords field for namedPlaces, as it doesn't exist in schema: https://schema.laji.fi/class/MNP.namedPlace

Let me know if you want me to add keyword to namedPlace schema and then display it on moth monitoring named place form

**Comment by rpulkka** [comment]
New changes done. I hadn't made dateBegin required, so that's why asterisk was missing :) .

**Comment by mikkohei13** [comment]
@rpulkka Form shows error on save:

![Image](https://github.com/user-attachments/assets/245bdd83-428c-49ca-b717-4906675c8111)

**Comment by rpulkka** [comment]
@mikkohei13 I tried twice, couldn't repro, for example: https://dev.laji.fi/view?uri=http:%2F%2Ftun.fi%2FJX.325272

Can you give more details on how to repro?

**Comment by mikkohei13** [comment]
It seems the error is triggered when there are no observations (units) on the form.

In theory, having no observations is a valid use case, so the form should handle it.

**Comment by rpulkka** [comment]
@mikkohei13 Thanks, now that case works also.
