### ISSUE TITLE
Add option to hide batch file generator on Vihko

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji#567]
Vihko form option to hide batch file generator when import is allowed.

By default generator should be open when import is allowed: this is how other forms should work.

**Comment by olzraiti** [comment]
@mikkohei13 testable in http://567.dev.laji.fi/project/MHL.1136/about

**Comment by mikkohei13** [comment]
- Sidebar does not show link to ./generate -> ok
- ./generate page does now work: buttons are disabled. -> should work, if user manually enter the url of this page. Or optionally only for admins.
- When user not logged in, the ./about page gives Hups-warking and error on console:

![Image](https://github.com/user-attachments/assets/4d3025ff-a18e-46d2-851f-61c3a4200735)

**Comment by olzraiti** [comment]
I updated it to work so that:

* sidebar generate page is shown if user is form admin
* generate page works if used is form admin

So admin bypasses the option that prevents the generate tool.

> When user not logged in, the ./about page gives Hups-warking and error on console:

Couldn't repro, maybe already fixed and unrelated to this task?
