### ISSUE TITLE
Fix NAFI saving failing for non-admins

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji#610]
Repro:

- Login to Laji.fi as a person who is neither ICT admin nor NAFI form admin
- Go to https://laji.fi/project/MHL.6/form
- Enter mandatory info and save 

Expected:

- Save ok

Actual:

- Anteeksi jokin meni pieleen -error
- Console shows https://laji.fi/api/documents?personToken= [HTTP/1.1 403 Forbidden 131ms]

**Comment by olzraiti** [comment]
The bug was introduced by broken fix to #600.
