### ISSUE TITLE
Create censuses-tab for the Bird Point Count result service

### ISSUE THREAD

**Issue by rpulkka** [luomus/laji#611]
Create censuses-tab which lists all Bird Point Count documents by year.

**Comment by rpulkka** [comment]
https://613.dev.laji.fi/project/MHL.75/stats?tab=censuses

Censuses-tab list testable here.

**Comment by wkmor1** [comment]
ping @mikkohei13

**Comment by mikkohei13** [comment]
@rpulkka Got Hups-error and this:

![Image](https://github.com/user-attachments/assets/b5c03e1d-0510-4fdf-bc26-ec9d04aa6ae0)

**Comment by rpulkka** [comment]
@mikkohei13 That issue seems to happen in on some other result services too, and not only in the feature branch, for example: https://dev.laji.fi/project/MHL.3/stats?tab=censuses

I'll ask about this on Slack and then I'll write an issue if needed. Doesn't occur on prod.

**Comment by rpulkka** [comment]
Until that's fixed, you need to login first, then navigate to the censuses page.

**Comment by mikkohei13** [comment]
Works ok. Can you make it sort the documents by date saved, descending, so that the latest document is first? This would make it easy for observers to find and check their data after they have saved it.

**Comment by rpulkka** [comment]
@mikkohei13 Testable here, remember to login before navigating to the result service: https://613.dev.laji.fi/

**Comment by mikkohei13** [comment]
Accessing page https://613.dev.laji.fi/project/MHL.75/stats?tab=censuses
gives Hups error and this in console (with Firefox 132)

![Image](https://github.com/user-attachments/assets/589eab9d-3fa3-4bb8-8875-cc1a666ea453)

**Comment by rpulkka** [comment]
@mikkohei13 Can be tested here: https://613.dev.laji.fi/project/MHL.75/stats?tab=censuses
