### ISSUE TITLE
Remove hakutoiminto toimii uudella tavalla -modal

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji#625]
When user accesses observation search for the first time (or in incognito), it shows a modal/notification about "hakutoiminto toimii uudella tavalla".

Remove this modal.

Keep the code, and keep the translations on Crowdin, since we might need this again when we do major changes to the UI.

**Comment by MLumme** [comment]
Testable here: https://625.dev.laji.fi/, as requested the code is intact, just commented out.

**Comment by mikkohei13** [comment]
Tested with Firefox & Edge.
