### ISSUE TITLE
Fix Vihko named place bugs

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji#630]
Esko 8.4.2024: I marked these as bugs because AFAIK these have worked before!

Mikko 30.10.2024: Another option would be to redesign the whole named place UI, if that doesn't take much more work than fixing these. Currently handling the named places is somewhat counterintuitive.

## Bug 1 - nothing happens after named place deletion 

- Go to https://dev.laji.fi/project/JX.519/form
- "Käytä omaa paikkaa"
- Select one place
- Press "Delete", confirm
- -> Place is deleted but UI just shows spinner forever

Should: Say some kind of confirmation and close dialog

## Bug 2 - saving named place with same name should override

- Go to https://dev.laji.fi/project/JX.519/form
- "Käytä omaa paikkaa"
- Check place name you have (and where it is)
- Close dialog, add some geometry to map using map drawing tools
 - "Tallenna omana paikkana"
 - Type name of existing place name -> save

Should: asks to confirm overriding previous place and overrides data

What happens: nothing: the old place remains, the new place has not been created

**Comment by MLumme** [comment]
Fixed, was a laji-form issue, so available now directly at dev.laji.fi.

**Comment by mikkohei13** [comment]
Works with Firefox 131.
