### ISSUE TITLE
Route feature branches to new API

### ISSUE THREAD

**Issue by rpulkka** [luomus/laji#666]
Currently dev.laji.fi points to the old API, which is deprecated. Feature branches use dev.laji.fi, therefore they're also routed to the old API.

How to fix: Add 'sed' command here https://ci.laji.fi/job/task.dev.laji.fi/configure to get feature branch to use eg [123.dev.laji.fi/api](http://123.dev.laji.fi/api) instead of [dev.laji.fi/api](http://dev.laji.fi/api)

How to test: For example https://dev.laji.fi/project/MHL.3/stats?tab=censuses returns hups error if not logged in (old API). Doesn't occur in the new API.

**Comment by olzraiti** [comment]
Done
